/*
 * Selling Partner API for Retail Procurement Orders
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.vendorOrders.api;

import com.amazon.SellingPartnerAPIAA.LWAException;
import com.amazon.spapi.ApiException;
import com.amazon.spapi.vendorOrders.model.*;
import org.junit.Ignore;
import org.junit.Test;
import org.threeten.bp.OffsetDateTime;

/**
* API tests for VendorOrdersApi
*/
@Ignore
public class VendorOrdersApiTest {

private final VendorOrdersApi api = new VendorOrdersApi();


/**
* 
*
* Returns a purchase order based on the purchaseOrderNumber value that you specify.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void getPurchaseOrderTest() throws ApiException, LWAException {
    String purchaseOrderNumber = null;
GetPurchaseOrderResponse response = api.getPurchaseOrder(purchaseOrderNumber);

// TODO: test validations
}

/**
* 
*
* Returns a list of purchase orders created or changed during the time frame that you specify. You define the time frame using the createdAfter, createdBefore, changedAfter and changedBefore parameters. The date range to search must not be more than 7 days. You can choose to get only the purchase order numbers by setting includeDetails to false. You can then use the getPurchaseOrder operation to receive details for a specific purchase order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void getPurchaseOrdersTest() throws ApiException, LWAException {
    Long limit = null;
    OffsetDateTime createdAfter = null;
    OffsetDateTime createdBefore = null;
    String sortOrder = null;
    String nextToken = null;
    String includeDetails = null;
    OffsetDateTime changedAfter = null;
    OffsetDateTime changedBefore = null;
    String poItemState = null;
    String isPOChanged = null;
    String purchaseOrderState = null;
    String orderingVendorCode = null;
GetPurchaseOrdersResponse response = api.getPurchaseOrders(limit, createdAfter, createdBefore, sortOrder, nextToken, includeDetails, changedAfter, changedBefore, poItemState, isPOChanged, purchaseOrderState, orderingVendorCode);

// TODO: test validations
}

/**
* 
*
* Returns purchase order statuses based on the filters that you specify. Date range to search must not be more than 7 days. You can return a list of purchase order statuses using the available filters, or a single purchase order status by providing the purchase order number.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void getPurchaseOrdersStatusTest() throws ApiException, LWAException {
    Long limit = null;
    String sortOrder = null;
    String nextToken = null;
    OffsetDateTime createdAfter = null;
    OffsetDateTime createdBefore = null;
    OffsetDateTime updatedAfter = null;
    OffsetDateTime updatedBefore = null;
    String purchaseOrderNumber = null;
    String purchaseOrderStatus = null;
    String itemConfirmationStatus = null;
    String itemReceiveStatus = null;
    String orderingVendorCode = null;
    String shipToPartyId = null;
GetPurchaseOrdersStatusResponse response = api.getPurchaseOrdersStatus(limit, sortOrder, nextToken, createdAfter, createdBefore, updatedAfter, updatedBefore, purchaseOrderNumber, purchaseOrderStatus, itemConfirmationStatus, itemReceiveStatus, orderingVendorCode, shipToPartyId);

// TODO: test validations
}

/**
* 
*
* Submits acknowledgements for one or more purchase orders.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 10 | 10 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void submitAcknowledgementTest() throws ApiException, LWAException {
    SubmitAcknowledgementRequest body = null;
SubmitAcknowledgementResponse response = api.submitAcknowledgement(body);

// TODO: test validations
}

}