/*
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.shipping.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Info About Linkable Account Type
 */
@ApiModel(description = "Info About Linkable Account Type")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-06-27T19:00:59.419+08:00")
public class LinkableAccountType {
  @SerializedName("accountType")
  private AccountType accountType = null;

  @SerializedName("carrierAccountInputs")
  private CarrierAccountInputsList carrierAccountInputs = null;

  public LinkableAccountType accountType(AccountType accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  @ApiModelProperty(value = "")
  public AccountType getAccountType() {
    return accountType;
  }

  public void setAccountType(AccountType accountType) {
    this.accountType = accountType;
  }

  public LinkableAccountType carrierAccountInputs(CarrierAccountInputsList carrierAccountInputs) {
    this.carrierAccountInputs = carrierAccountInputs;
    return this;
  }

   /**
   * Get carrierAccountInputs
   * @return carrierAccountInputs
  **/
  @ApiModelProperty(value = "")
  public CarrierAccountInputsList getCarrierAccountInputs() {
    return carrierAccountInputs;
  }

  public void setCarrierAccountInputs(CarrierAccountInputsList carrierAccountInputs) {
    this.carrierAccountInputs = carrierAccountInputs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkableAccountType linkableAccountType = (LinkableAccountType) o;
    return Objects.equals(this.accountType, linkableAccountType.accountType) &&
        Objects.equals(this.carrierAccountInputs, linkableAccountType.carrierAccountInputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountType, carrierAccountInputs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkableAccountType {\n");
    
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    carrierAccountInputs: ").append(toIndentedString(carrierAccountInputs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

